services:
  frontend:
    container_name: zapsign-frontend
    build:
      context: .
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start -- --host 0.0.0.0
    networks:
      - zapsign-network

networks:
  zapsign-network:
    name: zapsign-network
